apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "beer" | repeat 3 }}
  food: {{ quote $.Values.favorite.food | upper }}
  ip: {{ getHostByName .hostname }}
  {{- end }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}

